### ISSUE TITLE
gk skips a line if cursor is at column 0 position (Obsidian)

### ISSUE THREAD

**Issue by apotenza92** [replit/codemirror-vim#165]
Hi, 

Originally saw this discussed on the Obsidian forums [here](https://forum.obsidian.md/t/vim-gk-at-the-head-of-line-goes-2-line-up/74445) and it was suggested to make an issue here.

If cursor is at the start of a line (i.e. column 1) position then a `gk` command moves up two lines instead of one.
If cursor is at any other column position `gk` works correctly.

`gj` works correctly at all column positions.

## Steps to reproduce
Open a file with wrapped long paragraph. Make sure vim is open and it is in view mode.
gg: curosr at first line
gj x 2: cursor to third line
gk: cursor to the first line rather than second
Expected result
In vim view mode, pressing gk leads to 1 viewing line up.

## Actual result
Pressing gk leads to 2 viewing line up if cursor is at the head of one line.

## Environment
Obsidian vim mode

## Additional information
gj works fine. gk works also if cursor at the middle of a line.

**Comment by Opisek** [comment]
For clarification, this only happens when the line is wrapped, correct?

**Comment by apotenza92** [comment]
Yes that's correct. Apologies I should've mentioned that.

**Comment by Opisek** [comment]
I'm afraid this is a CodeMirror issue, rather than CodeMirror Vim.

The unexpected behaviour is generated [here](https://github.com/replit/codemirror-vim/blob/70bf0f188197d07bc02a4ba364746a9f0d0ec79a/src/cm_adapter.ts#L549) and does exactly what described in the issue.

Example:
- My lines are 100 characters long.
- My first line contains a 100 letters.
- My second line contains 200 letters and wraps.
- Let the cursor be on the first character of the third line (wrapped second line).
- The cursor position is 200.
- Calling CodeMirror's `moveVertically` will return 0 instead of 100.

I am unsure if this is the intended behaviour of the relevant function. A monkey-patch on our end would be to artificially move the cursor one character to the right and then back to the left, but I imagine that would introduce even more bugs.

I believe this issue should be taken to CodeMirror directly, however, I wasn't able to find the repository responsible for that part.

**Comment by nightwing** [comment]
@Opisek seems  to be a bug in [EditorSelection.range](https://codemirror.net/docs/ref/#state.EditorSelection^range) which creates a cursor that is displayed as a range with `assoc=1`, but behaves as one with `assoc=-1`
